In [1]:
import pandas as pd
import numpy as np

import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
df = pd.read_csv("Titanic-Dataset.csv")

In [3]:
df.head()

df.info()

df.describe()

df.shape

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    object
 4   Sex          891 non-null    object
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object
 11  Embarked     889 non-null    object
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB

(891, 12)

In [4]:
df.isnull().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

In [5]:
df.duplicated().sum()

np.int64(0)

In [6]:
df.dtypes

PassengerId      int64
Survived         int64
Pclass           int64
Name            object
Sex             object
Age            float64
SibSp            int64
Parch            int64
Ticket          object
Fare           float64
Cabin           object
Embarked        object
dtype: object

In [7]:
df.describe()

,PassengerId,Survived,Pclass,Age,SibSp,Parch,Fare
count,891.000000,891.000000,891.000000,714.000000,891.000000,891.000000,891.000000
mean,446.000000,0.383838,2.308642,29.699118,0.523008,0.381594,32.204208
std,257.353842,0.486592,0.836071,14.526497,1.102743,0.806057,49.693429
min,1.000000,0.000000,1.000000,0.420000,0.000000,0.000000,0.000000
25%,223.500000,0.000000,2.000000,20.125000,0.000000,0.000000,7.910400
50%,446.000000,0.000000,3.000000,28.000000,0.000000,0.000000,14.454200
75%,668.500000,1.000000,3.000000,38.000000,1.000000,0.000000,31.000000
max,891.000000,1.000000,3.000000,80.000000,8.000000,6.000000,512.329200

In [8]:
df.isnull().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

In [10]:
df['Age'] = df['Age'].fillna(df['Age'].median())

In [12]:
df['Embarked'] = df['Embarked'].fillna(df['Embarked'].mode()[0])

In [13]:
df['Cabin'] = df['Cabin'].fillna("Unknown")

In [14]:
duplicates_before = df.duplicated().sum()

print(duplicates_before)

0

In [15]:
df.drop_duplicates(inplace=True)

In [16]:
duplicates_after = df.duplicated().sum()

print(duplicates_after)

0

In [17]:
df['Sex'] = df['Sex'].replace({
    'male':'Male',
    'Male':'Male',
    'M':'Male',

    'female':'Female',
    'Female':'Female',
    'F':'Female'
})

In [19]:
df['Sex'] = df['Sex'].replace({
    'male': 'Male',
    'female': 'Female'
})

In [21]:
print(df.columns)

Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked'],
      dtype='object')

In [22]:
Q1 = df['Age'].quantile(0.25)

Q3 = df['Age'].quantile(0.75)

IQR = Q3 - Q1

In [23]:
upper = Q3 + 1.5*IQR

In [24]:
lower = Q1 - 1.5*IQR

In [25]:
outliers = df[(df['Age']<lower) | (df['Age']>upper)]

outliers

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
7,8,0,3,"Palsson, Master. Gosta Leonard",Male,2.00,3,1,349909,21.0750,Unknown,S
11,12,1,1,"Bonnell, Miss. Elizabeth",Female,58.00,0,0,113783,26.5500,C103,S
15,16,1,2,"Hewlett, Mrs. (Mary D Kingcome)",Female,55.00,0,0,248706,16.0000,Unknown,S
16,17,0,3,"Rice, Master. Eugene",Male,2.00,4,1,382652,29.1250,Unknown,Q
33,34,0,2,"Wheadon, Mr. Edward H",Male,66.00,0,0,C.A. 24579,10.5000,Unknown,S
...,...,...,...,...,...,...,...,...,...,...,...,...
827,828,1,2,"Mallet, Master. Andre",Male,1.00,0,2,S.C./PARIS 2079,37.0042,Unknown,C
829,830,1,1,"Stone, Mrs. George Nelson (Martha Evelyn)",Female,62.00,0,0,113572,80.0000,B28,S
831,832,1,2,"Richards, Master. George Sibley",Male,0.83,1,1,29106,18.7500,Unknown,S
851,852,0,3,"Svensson, Mr. Johan",Male,74.00,0,0,347060,7.7750,Unknown,S
879,880,1,1,"Potter, Mrs. Thomas Jr (Lily Alexenia Wilson)",Female,56.00,0,1,11767,83.1583,C50,C

In [26]:
df = df[(df['Age']>=lower) & (df['Age']<=upper)]

In [28]:
df = df.copy()

df.loc[:, 'Age'] = np.where(df['Age'] > upper, upper, df['Age'])
df.loc[:, 'Age'] = np.where(df['Age'] < lower, lower, df['Age'])

In [29]:
df.dtypes

PassengerId      int64
Survived         int64
Pclass           int64
Name            object
Sex             object
Age            float64
SibSp            int64
Parch            int64
Ticket          object
Fare           float64
Cabin           object
Embarked        object
dtype: object

In [30]:
df['PassengerId'] = df['PassengerId'].astype(str)

In [31]:
df['Fare'] = df['Fare'].astype(float)

In [33]:
# Save original statistics BEFORE cleaning
original_rows = len(df)
original_nulls = df.isnull().sum().sum()   # Total null values
original_duplicates = df.duplicated().sum()

print(original_rows)
print(original_nulls)
print(original_duplicates)

825
0
0

In [34]:
summary = pd.DataFrame({
    'Before': [original_rows, original_nulls, original_duplicates],
    'After': [
        len(df),
        df.isnull().sum().sum(),
        df.duplicated().sum()
    ]
}, index=['Rows', 'Null Values', 'Duplicates'])

summary

             Before  After
Rows            825    825
Null Values       0      0
Duplicates        0      0

In [35]:
summary = pd.DataFrame({

'Before':[original_rows,
          original_nulls,
          original_duplicates],

'After':[len(df),
         df.isnull().sum().sum(),
         df.duplicated().sum()]

},

index=['Rows',
        'Null Values',
        'Duplicates'])

summary

             Before  After
Rows            825    825
Null Values       0      0
Duplicates        0      0

In [36]:
after = {

'Rows': len(df),

'Null Values': df.isnull().sum().sum(),

'Duplicates': df.duplicated().sum()

}

In [37]:
df.to_csv("Cleaned_Titanic.csv", index=False)